spring.application.name=AbyssLogV2
spring.datasource.url=jdbc:postgresql://localhost:5432/AbyssLogDB
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

#trocar para update, quando for iniciar outro banco de dados em outro pc
spring.jpa.show-sql=true